name = "vida-familia-api"
main = "apps/worker/src/index.ts"
account_id = "ca7869ce6645cfb64973a55c625e1419"
compatibility_date = "2026-06-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
pages_build_output_dir = "apps/web/dist"



[vars]
PUBLIC_SITE_URL = "https://vidafamilia.es"
ALLOWED_ORIGINS = "http://localhost:5173,https://vidafamilia.es,https://www.vidafamilia.es"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "vida-familia-db"
database_id = "REPLACE_WITH_REAL_D1_DATABASE_ID_AFTER_RUNNING_WRANGLER_D1_CREATE"
migrations_dir = "migrations"