name = "vida-familia-api"
main = "apps/worker/src/index.ts"
account_id = "ca7869ce6645cfb64973a55c625e1419"
compatibility_date = "2026-06-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "vida-familia-db"
database_id = "8efefb70-f96c-4fc6-b525-2b0300528b2a"
migrations_dir = "migrations"