import type { Locale } from "@vida-familia/shared";
import { ArrowUpLeft, BookOpen, BriefcaseBusiness, Building2, GraduationCap, Heart, Home, Mail, MapPin, PhoneCall } from "lucide-react";
import { Link } from "react-router-dom";
import { ContactForm } from "../components/ContactForm";
import { DisclaimerBox } from "../components/DisclaimerBox";
import { GuideUnlockSection } from "../components/GuideUnlockSection";
import { LeadForm } from "../components/LeadForm";
import { NewsletterForm } from "../components/NewsletterForm";
import { PageShell } from "../components/PageShell";
import { QualificationCTA } from "../components/QualificationCTA";
import { SectionHeading } from "../components/SectionHeading";
import { destinations, servicePages } from "../data/siteData";
import { routeFor } from "../lib/locale";

const pageCopy = {
  fa: {
    aboutTitle: "یک خانواده؛ دو کشور؛ یک روایت صادقانه", aboutIntro: "ویدا فامیلیا از تجربه واقعی تحصیل، کار، خانواده و ساختن زندگی میان اسپانیا و آرژانتین شکل گرفته است.",
    aboutLead: "ما این مسیر را از پشت میز شروع نکردیم.", aboutBody: "از انتخاب مدرسه و دانشگاه تا خانه، بانک، بیمه، مدارک و روزهای پرابهام اول را زندگی کرده‌ایم. هدف ما فروش رؤیا نیست؛ تبدیل تجربه پراکنده به یک مسیر قابل‌فهم برای افراد جدی است.",
    servicesTitle: "مسیر درست، قبل از خدمات بیشتر", servicesIntro: "خدمات ما از ارزیابی تناسب مسیر شروع می‌شود و فقط تا جایی ادامه پیدا می‌کند که برای پرونده شما معنا داشته باشد.",
    resourcesTitle: "راهنماهایی برای تصمیم بهتر", resourcesIntro: "محتوای ویدا فامیلیا برای دیدن واقعیت زندگی، هزینه، تحصیل و کار پیش از تصمیم طراحی شده است.",
    applyTitle: "اول تناسب مسیر را بررسی کنیم", applyIntro: "این یک فرم فروش نیست؛ نقطه شروع یک ارزیابی واقع‌بینانه و محترمانه است.",
    contactTitle: "یک گفت‌وگوی روشن، نه یک وعده مبهم", contactIntro: "برای سؤال عمومی یا همکاری پیام بگذارید. ارزیابی پرونده‌های شخصی از طریق فرم ارزیابی انجام می‌شود.",
  },
  en: {
    aboutTitle: "One family. Two countries. An honest story.", aboutIntro: "Vida Familia grew from real experience of study, work, family and rebuilding life across Spain and Argentina.",
    aboutLead: "We did not begin this journey behind a desk.", aboutBody: "We have lived the decisions around school, university, housing, banking, insurance, paperwork and uncertain first days. Our purpose is not to sell a dream; it is to turn scattered experience into a clear path for serious people.",
    servicesTitle: "The right path before more services", servicesIntro: "Our work starts by assessing fit and continues only as far as it genuinely serves your case.",
    resourcesTitle: "Guides for better decisions", resourcesIntro: "Vida Familia content helps you see real life, cost, study and work before deciding.",
    applyTitle: "Let us assess fit first", applyIntro: "This is not a sales form; it is the start of a realistic, respectful assessment.",
    contactTitle: "A clear conversation, not a vague promise", contactIntro: "Leave a note for general questions or partnerships. Personal case assessments begin through the assessment form.",
  },
  es: {
    aboutTitle: "Una familia. Dos países. Una historia honesta.", aboutIntro: "Vida Familia nace de una experiencia real de estudios, trabajo, familia y reconstrucción de vida entre España y Argentina.",
    aboutLead: "No empezamos este viaje detrás de un escritorio.", aboutBody: "Hemos vivido las decisiones sobre colegios, universidad, vivienda, banca, seguros, documentos y los inciertos primeros días. No vendemos un sueño: convertimos experiencia dispersa en un camino claro para personas serias.",
    servicesTitle: "La vía correcta antes que más servicios", servicesIntro: "Nuestro trabajo comienza valorando el encaje y continúa solo cuando aporta valor real al caso.",
    resourcesTitle: "Guías para decidir mejor", resourcesIntro: "El contenido de Vida Familia muestra vida, costes, estudios y trabajo reales antes de decidir.",
    applyTitle: "Primero evaluamos el encaje", applyIntro: "No es un formulario comercial; es el inicio de una evaluación realista y respetuosa.",
    contactTitle: "Una conversación clara, no una promesa vaga", contactIntro: "Escríbenos para preguntas generales o colaboraciones. La evaluación personal comienza con el formulario.",
  },
} as const;

export function AboutPage({ locale }: { locale: Locale }) {
  const c = pageCopy[locale];
  const principles = locale === "fa" ? [["واقعیت قبل از آرزو", "هزینه‌ها، محدودیت‌ها و اشتباه‌ها را هم می‌گوییم."], ["خانواده به‌عنوان یک کل", "تصمیم یک نفر بر تحصیل، کار و آرامش همه اثر دارد."], ["تخصص در جای درست", "موضوع حقوقی یا مالیاتی را به متخصص دارای صلاحیت می‌سپاریم."], ["فرایند به‌جای فشار", "نه فوریت ساختگی داریم و نه وعده نتیجه قطعی."]] : locale === "es" ? [["Realidad antes que ilusión", "También hablamos de costes, límites y errores."], ["La familia como conjunto", "Cada decisión afecta estudios, trabajo y bienestar de todos."], ["Experiencia donde corresponde", "Derivamos lo jurídico o fiscal a profesionales habilitados."], ["Proceso, no presión", "Sin urgencia falsa ni promesas de resultado."]] : [["Reality before aspiration", "We also discuss costs, limits and mistakes."], ["The family as a whole", "Each decision affects everyone's study, work and wellbeing."], ["Expertise in the right place", "Legal and tax matters go to qualified professionals."], ["Process, not pressure", "No fake urgency and no promised outcome."]];
  return <PageShell locale={locale} eyebrow="OUR STORY" title={c.aboutTitle} intro={c.aboutIntro} path="/about"><section className="content-section editorial-story"><div><p className="eyebrow">WHY VIDA FAMILIA</p><h2>{c.aboutLead}</h2></div><p>{c.aboutBody}</p></section><section className="content-section"><SectionHeading eyebrow="OUR STANDARD" title={locale === "fa" ? "چیزی که به آن پایبندیم" : locale === "es" ? "Nuestros principios" : "What we stand for"} /><div className="principles-grid">{principles.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><QualificationCTA locale={locale} /></PageShell>;
}

export function DestinationPage({ locale, country }: { locale: Locale; country: "spain" | "argentina" }) {
  const data = destinations.find((item) => item.country === country);
  if (!data) return null;
  const title = data.title[locale];
  const intro = data.description[locale];
  const services = servicePages.filter((item) => item.country === country);
  const practical = country === "spain" ? ["NIE / TIE", "Empadronamiento", "Banking", "Housing", "Insurance", "Tax coordination", "School enrollment", "Translation"] : ["DNI", "CDI / CUIL", "Certificado de domicilio", "Banking", "Housing", "Insurance", "School enrollment", "Translation"];
  return <PageShell locale={locale} eyebrow={`${country.toUpperCase()} · DESTINATION`} title={title} intro={intro} path={`/${country}`} tone={country}><section className="content-section editorial-story"><div><p className="eyebrow">REAL LIFE</p><h2>{locale === "fa" ? `زندگی در ${title} فقط پرونده اقامت نیست` : locale === "es" ? `Vivir en ${title} no es solo un expediente` : `Life in ${title} is more than an application`}</h2></div><p>{locale === "fa" ? "محله، هزینه، مدرسه، زبان، رفت‌وآمد و شبکه حمایتی به اندازه مدارک اهمیت دارند. برنامه ما این تصمیم‌ها را در یک تصویر واحد کنار هم می‌گذارد." : locale === "es" ? "Barrio, costes, colegios, idioma, transporte y red de apoyo importan tanto como los documentos. Nuestro plan conecta todas estas decisiones." : "Neighborhood, cost, school, language, transport and support networks matter as much as documents. Our plan connects them."}</p></section><section className="content-section"><SectionHeading eyebrow="PATHWAYS" title={locale === "fa" ? "مسیرهای اصلی" : locale === "es" ? "Vías principales" : "Core pathways"} /><div className="pathway-grid">{services.map((service) => <Link key={service.slug} to={routeFor(locale, `/services/${country}/${service.slug}`)}><span>{country === "spain" ? "ES" : "AR"}</span><h3>{service.title[locale]}</h3><p>{service.summary[locale]}</p><ArrowUpLeft /></Link>)}</div></section><section className="content-section tinted-section"><SectionHeading eyebrow="SETTLEMENT" title={locale === "fa" ? "جزئیات زندگی روزمره" : locale === "es" ? "Detalles de la vida diaria" : "Everyday settlement details"} /><div className="tag-cloud">{practical.map((item) => <span key={item}>{item}</span>)}</div></section><QualificationCTA locale={locale} /><DisclaimerBox>{locale === "fa" ? "شرایط اقامت، مالیات، کار و تابعیت تغییرپذیر و پرونده‌محور است. این صفحه آموزشی است و باید پیش از اقدام با منبع رسمی و متخصص مناسب تأیید شود." : locale === "es" ? "Residencia, fiscalidad, trabajo y ciudadanía cambian y dependen del caso. Confirma la información con fuentes oficiales y profesionales." : "Residency, tax, work and citizenship rules change and depend on the case. Confirm information with official sources and qualified professionals."}</DisclaimerBox></PageShell>;
}

export function ServicesPage({ locale }: { locale: Locale }) {
  const c = pageCopy[locale];
  return <PageShell locale={locale} eyebrow="SERVICES" title={c.servicesTitle} intro={c.servicesIntro} path="/services"><section className="content-section"><div className="pathway-grid pathway-grid-wide">{servicePages.map((service) => <Link key={`${service.country}-${service.slug}`} to={routeFor(locale, `/services/${service.country}/${service.slug}`)}><span>{service.country === "spain" ? "ES" : "AR"}</span><h3>{service.title[locale]}</h3><p>{service.summary[locale]}</p><ArrowUpLeft /></Link>)}</div></section><section className="content-section"><SectionHeading eyebrow="PRACTICAL SUPPORT" title={locale === "fa" ? "خدمات تکمیلی استقرار" : locale === "es" ? "Apoyo práctico de instalación" : "Practical settlement support"} /><div className="icon-feature-grid"><article><Home /><h3>Housing</h3><p>{locale === "fa" ? "استراتژی جست‌وجو، مدارک اجاره و هماهنگی عملی." : "Search strategy, rental documents and practical coordination."}</p></article><article><Building2 /><h3>Administration</h3><p>{locale === "fa" ? "ثبت‌های محلی، بانک، بیمه و زمان‌بندی امور." : "Local registrations, banking, insurance and timing."}</p></article><article><GraduationCap /><h3>Education</h3><p>{locale === "fa" ? "دانشگاه، مدرسه، زبان و انطباق تحصیلی." : "University, school, language and academic transition."}</p></article><article><BriefcaseBusiness /><h3>Business</h3><p>{locale === "fa" ? "هماهنگی ساختار کسب‌وکار و ارجاع تخصصی." : "Business structure coordination and specialist referrals."}</p></article></div></section><QualificationCTA locale={locale} /></PageShell>;
}

export function LifestylePage({ locale, type }: { locale: Locale; type: "family-life" | "student-life" | "business-residency" }) {
  const info = {
    "family-life": { icon: Heart, title: { fa: "زندگی خانوادگی", en: "Family life", es: "Vida familiar" }, intro: { fa: "مدرسه، محله، سلامت، زبان و ریتم روزمره؛ چیزهایی که کیفیت واقعی جابه‌جایی را می‌سازند.", en: "School, neighborhood, health, language and daily rhythm—the ingredients of a real family move.", es: "Colegio, barrio, salud, idioma y ritmo diario: lo que define un traslado familiar real." } },
    "student-life": { icon: BookOpen, title: { fa: "زندگی دانشجویی", en: "Student life", es: "Vida estudiantil" }, intro: { fa: "پذیرش فقط آغاز است؛ زبان، بودجه، خانه و سازگاری تعیین می‌کنند تجربه تحصیل چگونه پیش می‌رود.", en: "Admission is only the beginning; language, budget, housing and adaptation shape the experience.", es: "La admisión es solo el comienzo; idioma, presupuesto, vivienda y adaptación definen la experiencia." } },
    "business-residency": { icon: BriefcaseBusiness, title: { fa: "کسب‌وکار و اقامت", en: "Business & residency", es: "Empresa y residencia" }, intro: { fa: "تصمیم‌های شرکتی، حرفه‌ای، مالیاتی و خانوادگی باید از ابتدا با هم دیده شوند.", en: "Company, professional, tax and family decisions need one coherent plan from the start.", es: "Empresa, profesión, fiscalidad y familia necesitan un plan coherente desde el inicio." } },
  }[type];
  const Icon = info.icon;
  return <PageShell locale={locale} eyebrow="LIVED EXPERIENCE" title={info.title[locale]} intro={info.intro[locale]} path={`/${type}`}><section className="content-section lifestyle-focus"><Icon /><div><h2>{locale === "fa" ? "واقعیت‌های کوچک، تصمیم‌های بزرگ" : locale === "es" ? "Pequeñas realidades, grandes decisiones" : "Small realities, big decisions"}</h2><p>{locale === "fa" ? "محتوای این بخش به‌تدریج با راهنماهای میدانی، تجربه‌های خانواده و گفت‌وگو با متخصصان تکمیل می‌شود. نسخه نخست، چارچوب تصمیم و مسیرهای مرتبط را در اختیار شما می‌گذارد." : locale === "es" ? "Esta sección crecerá con guías de campo, experiencias familiares y conversaciones profesionales. La primera versión ofrece el marco y las vías relacionadas." : "This section will grow with field guides, family experience and professional conversations. The first release provides a decision framework and related pathways."}</p></div></section><QualificationCTA locale={locale} /></PageShell>;
}

export function ResourcesPage({ locale }: { locale: Locale }) {
  const c = pageCopy[locale];
  const items = locale === "fa" ? [["مادرید", "بودجه ماه اول زندگی خانوادگی"], ["دانشجو", "پرسش‌هایی که پیش از انتخاب دوره باید بپرسید"], ["بوئنوس آیرس", "مدارک مبدا را از کجا شروع کنیم؟"], ["نومد", "درآمد آنلاین با پرونده قابل دفاع چه تفاوتی دارد؟"], ["خانواده", "مدرسه، خانه و زمان‌بندی جابه‌جایی"]] : locale === "es" ? [["Madrid", "Presupuesto del primer mes en familia"], ["Estudios", "Preguntas antes de elegir programa"], ["Buenos Aires", "Por dónde empezar los documentos de origen"], ["Nómada", "Ingresos online y expediente demostrable"], ["Familia", "Colegio, vivienda y calendario de traslado"]] : [["Madrid", "A family first-month budget"], ["Study", "Questions before choosing a program"], ["Buenos Aires", "Where to start origin documents"], ["Nomad", "Online income versus a defensible file"], ["Family", "School, housing and relocation timing"]];
  return <PageShell locale={locale} eyebrow="FIELD NOTES" title={c.resourcesTitle} intro={c.resourcesIntro} path="/resources"><section className="content-section resources-grid">{items.map(([category, title], index) => <article key={title}><span>{category}</span><small>0{index + 1}</small><h2>{title}</h2><p>{locale === "fa" ? "این راهنما در تقویم محتوایی نسخه نخست قرار دارد." : locale === "es" ? "Esta guía forma parte del calendario editorial inicial." : "This guide is in the initial editorial calendar."}</p></article>)}</section><GuideUnlockSection locale={locale} /><NewsletterForm locale={locale} /><DisclaimerBox>{locale === "fa" ? "منابع در حال انتشارند. تاریخ و منبع به‌روزرسانی هر راهنما هنگام انتشار مشخص خواهد شد." : locale === "es" ? "Los recursos están en preparación. Cada guía publicada indicará fecha y fuentes." : "Resources are being prepared. Each published guide will show its date and sources."}</DisclaimerBox></PageShell>;
}

export function ApplyPage({ locale }: { locale: Locale }) { const c = pageCopy[locale]; return <PageShell locale={locale} eyebrow="ASSESSMENT" title={c.applyTitle} intro={c.applyIntro} path="/apply"><LeadForm locale={locale} /><DisclaimerBox>{locale === "fa" ? "ارسال فرم به‌معنای ایجاد رابطه حقوقی، پذیرش پرونده یا تضمین نتیجه نیست. اطلاعات فقط برای ارزیابی و تماس استفاده می‌شود." : locale === "es" ? "Enviar el formulario no crea relación jurídica, aceptación del caso ni garantía. Los datos se usan para evaluación y contacto." : "Submitting does not create a legal relationship, case acceptance or guarantee. Data is used for assessment and contact only."}</DisclaimerBox></PageShell>; }

export function ContactPage({ locale }: { locale: Locale }) {
  const c = pageCopy[locale];
  return <PageShell locale={locale} eyebrow="CONTACT" title={c.contactTitle} intro={c.contactIntro} path="/contact"><section className="content-section contact-grid"><article><Mail /><p className="eyebrow">GENERAL</p><h2>{locale === "fa" ? "پیام عمومی" : locale === "es" ? "Consulta general" : "General enquiry"}</h2><p>{locale === "fa" ? "نشانی ایمیل رسمی پیش از راه‌اندازی نهایی توسط مالک اضافه می‌شود." : locale === "es" ? "El correo oficial se añadirá antes del lanzamiento." : "The official email address will be added by the owner before launch."}</p></article><article><PhoneCall /><p className="eyebrow">CASE ASSESSMENT</p><h2>{locale === "fa" ? "بررسی پرونده" : locale === "es" ? "Evaluación de caso" : "Case assessment"}</h2><p>{locale === "fa" ? "برای حفظ نظم و حریم خصوصی، ارزیابی از فرم اختصاصی آغاز می‌شود." : locale === "es" ? "Para mantener orden y privacidad, la evaluación comienza con el formulario." : "For privacy and structure, assessment begins with the dedicated form."}</p><Link className="text-link" to={routeFor(locale, "/apply")}>{locale === "fa" ? "رفتن به فرم" : locale === "es" ? "Ir al formulario" : "Open the form"}<ArrowUpLeft /></Link></article><article><MapPin /><p className="eyebrow">IRAN · SPAIN</p><h2>{locale === "fa" ? "کنگان · شیراز · مادرید" : "Kanghan · Shiraz · Madrid"}</h2><p>{locale === "fa" ? "جلسه حضوری فقط با هماهنگی قبلی و پس از ارزیابی اولیه انجام می‌شود." : locale === "es" ? "Las reuniones presenciales son solo con cita y evaluación previa." : "In-person meetings are by prior arrangement after initial assessment."}</p></article></section><ContactForm locale={locale} /></PageShell>;
}

export function LegalPage({ locale, type }: { locale: Locale; type: "privacy" | "terms" | "legal-disclaimer" }) {
  const content = {
    privacy: {
      title: { fa: "حریم خصوصی", en: "Privacy policy", es: "Política de privacidad" }, intro: { fa: "نحوه استفاده از اطلاعاتی که داوطلبانه در فرم‌ها ارائه می‌کنید.", en: "How we use information you voluntarily provide through forms.", es: "Cómo usamos la información que facilitas voluntariamente." },
      sections: locale === "fa" ? [["اطلاعاتی که دریافت می‌کنیم", "نام، اطلاعات تماس و پاسخ‌های ارزیابی که خودتان ارسال می‌کنید."], ["هدف استفاده", "فقط برای ارزیابی اولیه، پاسخگویی، امنیت و نگهداری سوابق ضروری."], ["نگهداری و دسترسی", "دسترسی محدود است و اطلاعات بیش از نیاز عملی نگهداری نمی‌شود. سیاست حذف نهایی پیش از راه‌اندازی توسط مالک تأیید می‌شود."], ["حقوق شما", "برای درخواست دسترسی، اصلاح یا حذف، از نشانی رسمی که پیش از راه‌اندازی درج می‌شود استفاده کنید."]] : locale === "es" ? [["Datos recogidos", "Nombre, contacto y respuestas que envías."], ["Finalidad", "Evaluación inicial, respuesta, seguridad y registros necesarios."], ["Conservación y acceso", "Acceso limitado y conservación solo durante el tiempo necesario. El propietario validará la política final antes del lanzamiento."], ["Tus derechos", "Podrás solicitar acceso, rectificación o eliminación en el correo oficial que se publicará."]] : [["Information collected", "Name, contact details and assessment answers you submit."], ["Purpose", "Initial assessment, response, security and necessary records only."], ["Retention and access", "Access is limited and data is not kept longer than operationally needed. The owner will confirm final retention before launch."], ["Your rights", "Use the official address published before launch to request access, correction or deletion."]],
    },
    terms: {
      title: { fa: "شرایط استفاده", en: "Terms of use", es: "Condiciones de uso" }, intro: { fa: "قواعد استفاده از وب‌سایت و ارتباط با ویدا فامیلیا.", en: "Rules for using this website and engaging with Vida Familia.", es: "Reglas para usar este sitio y relacionarse con Vida Familia." },
      sections: locale === "fa" ? [["استفاده آموزشی", "محتوا عمومی و آموزشی است و پیشنهاد حقوقی، مالیاتی یا مالی شخصی نیست."], ["عدم تضمین", "هیچ نتیجه ویزا، اقامت، پذیرش، کار یا تابعیت تضمین نمی‌شود."], ["پیشنهاد خدمات", "دامنه، هزینه، مسئولیت و شرایط هر همکاری فقط در پیشنهاد یا قرارداد مکتوب معتبر است."], ["مالکیت محتوا", "استفاده شخصی مجاز است؛ بازنشر تجاری بدون اجازه کتبی مجاز نیست."]] : locale === "es" ? [["Uso educativo", "El contenido es general y no constituye asesoramiento jurídico, fiscal o financiero personal."], ["Sin garantía", "No se garantiza visado, residencia, admisión, empleo ni ciudadanía."], ["Propuesta de servicios", "Alcance, precio y responsabilidades solo valen por escrito."], ["Contenido", "Se permite uso personal, no republicación comercial sin permiso."]] : [["Educational use", "Content is general and not personal legal, tax or financial advice."], ["No guarantee", "No visa, residency, admission, work or citizenship result is guaranteed."], ["Service proposals", "Scope, price and responsibility are valid only when agreed in writing."], ["Content ownership", "Personal use is allowed; commercial republication requires written permission."]],
    },
    "legal-disclaimer": {
      title: { fa: "سلب مسئولیت حقوقی", en: "Legal disclaimer", es: "Aviso legal" }, intro: { fa: "مرز خدمات آموزشی و هماهنگی ویدا فامیلیا با خدمات تخصصی تنظیم‌شده.", en: "The boundary between Vida Familia's education/coordination and regulated professional services.", es: "El límite entre educación/coordinación y servicios profesionales regulados." },
      sections: locale === "fa" ? [["ماهیت خدمات", "ویدا فامیلیا تجربه، آموزش جابه‌جایی و هماهنگی ارائه می‌دهد؛ دفتر وکالت یا مرجع دولتی نیست."], ["متخصصان مجاز", "امور حقوقی، مالیاتی یا مالی ممکن است به وکیل، حسابدار یا متخصص دارای مجوز ارجاع شود."], ["اطلاعات متغیر", "قوانین، مبالغ، رویه‌ها و زمان‌ها تغییر می‌کنند و باید پیش از اقدام از منبع رسمی تأیید شوند."], ["تصمیم نهایی", "تصمیم هر مرجع مستقل است و هیچ نتیجه‌ای تحت کنترل یا تضمین ویدا فامیلیا نیست."]] : locale === "es" ? [["Naturaleza", "Vida Familia ofrece experiencia, educación de reubicación y coordinación; no es un despacho ni autoridad."], ["Profesionales habilitados", "Lo jurídico, fiscal o financiero puede derivarse a profesionales habilitados."], ["Información cambiante", "Normas, importes, prácticas y plazos cambian y deben confirmarse oficialmente."], ["Decisión final", "Cada autoridad decide independientemente; Vida Familia no controla ni garantiza resultados."]] : [["Nature of service", "Vida Familia offers lived experience, relocation education and coordination; it is not a law firm or authority."], ["Licensed professionals", "Legal, tax or financial matters may be referred to qualified professionals."], ["Changing information", "Rules, amounts, practice and timing change and must be officially confirmed."], ["Final decision", "Authorities decide independently; Vida Familia neither controls nor guarantees results."]],
    },
  }[type];
  return <PageShell locale={locale} eyebrow="LEGAL" title={content.title[locale]} intro={content.intro[locale]} path={`/${type}`}><section className="content-section legal-copy"><p className="legal-updated">{locale === "fa" ? "نسخه آماده‌سازی پیش از راه‌اندازی · ۲۴ ژوئن ۲۰۲۶" : locale === "es" ? "Versión pre-lanzamiento · 24 junio 2026" : "Pre-launch version · 24 June 2026"}</p>{content.sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<DisclaimerBox>{locale === "fa" ? "مالک باید پیش از راه‌اندازی نهایی، هویت حقوقی، نشانی تماس، دوره نگهداری داده و الزامات محلی حریم خصوصی را با متخصص مناسب تأیید کند." : locale === "es" ? "Antes del lanzamiento, el propietario debe validar identidad legal, contacto, retención y requisitos locales con un profesional." : "Before launch, the owner should validate legal identity, contact details, retention period and local privacy requirements with a qualified professional."}</DisclaimerBox></section></PageShell>;
}
